version: "3.9"  # optional since v1.27.0
services:
  jupyter:
    build:
      dockerfile: dockerfile
    ports:
      - 8888:8888
      - 2224:22
    volumes:
      - ./notebooks/:/tf/notebooks
      - ./tmp/:/tmp
      -  ./:/code
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [ gpu ]